### ISSUE TITLE
Not work in anonymous mode

### ISSUE THREAD

**Issue by harp077** [dubasdey/portable-ftp-server#2]
Good day !
Many thanks for project !
But your server not work in anonymous mode - i'am sorry .....
I want to help you - my small project work in anonymous mode - see please: https://github.com/harp077/apache-ftp-server-my 
It is also based on Apache FTP server.

With best regards and respect,
Roman Koldaev

**Comment by dubasdey** [comment]
It was not planned to implement the anonymous mode as this small ftp portable server is in mind to offer a fast and secure way of transfer files between pc in a wide lan, like a corporate lan that has SMB or similar restrictions, and fort that the security is important . But if the community thinks that is a good improvement we could consider a flag for an anonymous mode. Thanks for the tip.
